# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

do_rgig1 <- function(lambda, chi, psi) {
    .Call('_pbcf_do_rgig1', PACKAGE = 'pbcf', lambda, chi, psi)
}

gig_norm <- function(lambda, chi, psi) {
    .Call('_pbcf_gig_norm', PACKAGE = 'pbcf', lambda, chi, psi)
}

checkFit <- function(y, mcmcdraws, probit, doWaic, sig = NULL, yobs = NULL) {
    .Call('_pbcf_checkFit', PACKAGE = 'pbcf', y, mcmcdraws, probit, doWaic, sig, yobs)
}

dmixnorm0 <- function(x, logprob, mu, sd) {
    .Call('_pbcf_dmixnorm0', PACKAGE = 'pbcf', x, logprob, mu, sd)
}

pmixnorm0 <- function(x, logprob, mu, sd) {
    .Call('_pbcf_pmixnorm0', PACKAGE = 'pbcf', x, logprob, mu, sd)
}

dmixnorm <- function(x, logprob, mu, sd) {
    .Call('_pbcf_dmixnorm', PACKAGE = 'pbcf', x, logprob, mu, sd)
}

pmixnorm <- function(x, logprob, mu, sd) {
    .Call('_pbcf_pmixnorm', PACKAGE = 'pbcf', x, logprob, mu, sd)
}

dmixnorm0_post <- function(x, mus, sd, logprobs) {
    .Call('_pbcf_dmixnorm0_post', PACKAGE = 'pbcf', x, mus, sd, logprobs)
}

pmixnorm0_post <- function(x, mus, sd, logprobs) {
    .Call('_pbcf_pmixnorm0_post', PACKAGE = 'pbcf', x, mus, sd, logprobs)
}

dmixnorm_post <- function(x, mus, sds, logprobs) {
    .Call('_pbcf_dmixnorm_post', PACKAGE = 'pbcf', x, mus, sds, logprobs)
}

pmixnorm_post <- function(x, mus, sds, logprobs) {
    .Call('_pbcf_pmixnorm_post', PACKAGE = 'pbcf', x, mus, sds, logprobs)
}

rpgmix <- function(n, a, m) {
    .Call('_pbcf_rpgmix', PACKAGE = 'pbcf', n, a, m)
}

probitbcf <- function(y, yobs, z, zpred, x_con, x_mod, xpred_con, xpred_mod, xinfo_list_con, xinfo_list_mod, nburn, nsim, ntree_con = 200L, ntree_mod = 50L, lambda = -999, sigq = .9, nu = 3, offset = 0, base_con = .95, power_con = 2.0, base_mod = .25, power_mod = 3.0, con_sd = 1, mod_sd = 1, use_muscale = FALSE, use_tauscale = FALSE, treef_name_ = "pbcf_trees.txt", save_trees = FALSE, silent_mode = FALSE, trt_init = 1.0) {
    .Call('_pbcf_probitbcf', PACKAGE = 'pbcf', y, yobs, z, zpred, x_con, x_mod, xpred_con, xpred_mod, xinfo_list_con, xinfo_list_mod, nburn, nsim, ntree_con, ntree_mod, lambda, sigq, nu, offset, base_con, power_con, base_mod, power_mod, con_sd, mod_sd, use_muscale, use_tauscale, treef_name_, save_trees, silent_mode, trt_init)
}

